# Generated by Django 4.1 on 2022-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_model_name_alter_car_msrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='msrp',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='MSRP'),
        ),
    ]
