# Generated by Django 4.1 on 2022-10-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_msrp'),
        ('sales', '0002_alter_sale_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sale Price'),
        ),
        migrations.CreateModel(
            name='SandboxSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sale Price')),
                ('sale_date', models.DateTimeField(verbose_name='Sale Date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
